name: Checks # workflow name

on:
  pull_request:
    types: [opened, synchronize] # workflow triggering events

jobs: # A workflow can have multiple jobs
  checks: # name of the job
    runs-on: ubuntu-latest # instance type where job will run

    steps:
      - name: "Checkout" # download code from repository
        uses: actions/checkout@v2 # public action
        with:
          fetch-depth: 0 # checkout all branches and tags

      - name: "Use NodeJS 14" # setup using node js v14
        uses: actions/setup-node@v2 # public action
        with:
          node-version: "14" # checkout all branches and tags

      - name: "Setup npm" # add our registry to npm config
        run: | # custom action
          npm set @benriquezm:registry=https://npm.pkg.github.com/benriquezm
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies # setup using node js v14
        run: | # Install and link dependencies
          npm ci
          npx lerna bootstrap
