name: Checks # workflow name

on:
  pull_request:
    types: [opened, synchronize] # workflow triggering events

jobs: # A workflow can have multiple jobs
  checks: # name of the job
    runs-on: ubuntu-latest # instance type where job will run

    steps:
      - name: "Checkout" # download code from repository
        uses: actions/checkout@v2 # public action
        with:
          fetch-depth: 0 # checkout all branches and tags

      - name: "Use NodeJS 14" # setup using node js v14
        uses: actions/setup-node@v2 # public action
        with:
          node-version: "14" # checkout all branches and tags
