name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - master
jobs:
  publish:
    if: github.event.pull_request.merged == true # condition only Pull Request merged
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout" # download code from repository
        uses: actions/checkout@v2 # public action
        with:
          fetch-depth: 0 # checkout all branches and tags

      - name: "Use NodeJS 14" # setup using node js v14
        uses: actions/setup-node@v2 # public action
        with:
          node-version: "14" # checkout all branches and tags

      - name: "Setup npm" # add our registry to npm config
        run: | # custom action
          npm set @benriquezm:registry=https://npm.pkg.github.com/benriquezm
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: "Version and publish"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git-config user.name "${{ github.actor }}"
          git-config user.email "${{ github.actor }}@users.noreply.github.com"

          if [ ${{ github.base_ref }} = develop ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          else
            npx lerna version --conventional-commits --conventional-graduate --yes

          npx lerna publish from-git --yes
